# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cicdaplicacion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3dfbd9d75463439c8c81f367706e79ab }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8dd33fb31ed844ddb90effa286cb13a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3dfbd9d75463439c8c81f367706e79ab }}/mitaller6:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cicdaplicacion'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e1574f49d28b48fea0ed3b8226fc700e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3dfbd9d75463439c8c81f367706e79ab }}/mitaller6:${{ github.sha }}'